local GameConfigs = {}

-- Economy
GameConfigs.BOX_COST = 100 
GameConfigs.MAX_INVENTORY_SLOTS = 50 -- 

-- Rarity Layers: Models
GameConfigs.MODELS = {
    -- SPECIAL / RARE (Lucky Blocks & Admin)
    { Name = "Admin Lucky Block",        Weight = 5, Multiplier = 10 },
    { Name = "Brainrot God Lucky Block", Weight = 1, Multiplier = 100 },
    { Name = "Mythic Lucky Block",       Weight = 3, Multiplier = 25 },
    { Name = "Secret Lucky Block",       Weight = 2, Multiplier = 50 },
    { Name = "Taco Lucky Block",         Weight = 5, Multiplier = 10 },

    -- STANDARD MODELS (Alphabetical from images)
    { Name = "67", Weight = 50, Multiplier = 1 },
    { Name = "Agarrini la Palini", Weight = 50, Multiplier = 1 },
    { Name = "Alessio", Weight = 50, Multiplier = 1 },
    { Name = "Antonio", Weight = 50, Multiplier = 1 },
    { Name = "Avocadini Antilopini", Weight = 50, Multiplier = 1 },
    { Name = "Avocadini Guffo", Weight = 50, Multiplier = 1 },
    { Name = "Avocadorilla", Weight = 50, Multiplier = 1 },
    { Name = "Ballerina Cappuccina", Weight = 50, Multiplier = 1 },
    { Name = "Ballerino Lololo", Weight = 50, Multiplier = 1 },
    { Name = "Bambini Crostini", Weight = 50, Multiplier = 1 },
    { Name = "Bananita Dolphinita", Weight = 50, Multiplier = 1 },
    { Name = "Bandito Axolito", Weight = 50, Multiplier = 1 },
    { Name = "Bandito Bobritto", Weight = 50, Multiplier = 1 },
    { Name = "Bisonte Giuppitere", Weight = 50, Multiplier = 1 },
    { Name = "Blackhole Goat", Weight = 20, Multiplier = 3 }, -- Sounds rare
    { Name = "Blueberrinni Octopusini", Weight = 50, Multiplier = 1 },
    { Name = "Bombardiro Crocodilo", Weight = 50, Multiplier = 1 },
    { Name = "Bombombini Gusini", Weight = 50, Multiplier = 1 },
    { Name = "Boneca Ambalabu", Weight = 50, Multiplier = 1 },
    { Name = "Brr Brr Patapim", Weight = 50, Multiplier = 1 },
    { Name = "Brr es Teh Patipum", Weight = 50, Multiplier = 1 },
    { Name = "Brri Brri Bicus Dicus Bombicus", Weight = 50, Multiplier = 1 },
    { Name = "Bulbito Bandito Traktorito", Weight = 50, Multiplier = 1 },
    { Name = "Burbaloni Loliloli", Weight = 50, Multiplier = 1 },
    { Name = "Cacasito Satalito", Weight = 50, Multiplier = 1 },
    { Name = "Cacto Hipopotamo", Weight = 50, Multiplier = 1 },
    { Name = "Cappuccino Assassino", Weight = 50, Multiplier = 1 },
    { Name = "Caramello Filtrello", Weight = 50, Multiplier = 1 },
    { Name = "Carloo", Weight = 50, Multiplier = 1 },
    { Name = "Carrotini Brainini", Weight = 50, Multiplier = 1 },
    { Name = "Cavallo Virtuoso", Weight = 50, Multiplier = 1 },
    { Name = "Celularcini Viciosini", Weight = 50, Multiplier = 1 },
    { Name = "Chachechi", Weight = 50, Multiplier = 1 },
    { Name = "Chef Crabracadabra", Weight = 50, Multiplier = 1 },
    { Name = "Chicleteira Bicicleteira", Weight = 50, Multiplier = 1 },
    { Name = "Chihuanini Taconini", Weight = 50, Multiplier = 1 },
    { Name = "Chimpanzini Bananini", Weight = 50, Multiplier = 1 },
    { Name = "Cocofanto Elefanto", Weight = 50, Multiplier = 1 },
    { Name = "Crabbo Limonetta", Weight = 50, Multiplier = 1 },
    { Name = "Dragon Cannelloni", Weight = 20, Multiplier = 3 }, -- Sounds rare
    { Name = "Dug dug dug", Weight = 50, Multiplier = 1 },
    { Name = "Dul Dul Dul", Weight = 50, Multiplier = 1 },
    { Name = "Esok Sekolah", Weight = 50, Multiplier = 1 },
    { Name = "Espresso Signora", Weight = 50, Multiplier = 1 },
    { Name = "Extinct Ballerina", Weight = 50, Multiplier = 1 },
    { Name = "Extinct Matteo", Weight = 50, Multiplier = 1 },
    { Name = "Extinct Tralalero", Weight = 50, Multiplier = 1 },
    { Name = "Fluriflura", Weight = 50, Multiplier = 1 },
    { Name = "Fragola La La La", Weight = 50, Multiplier = 1 },
    { Name = "Frigo Camelo", Weight = 50, Multiplier = 1 },
    { Name = "Ganganzelli Trulala", Weight = 50, Multiplier = 1 },
    { Name = "Gangster Footera", Weight = 50, Multiplier = 1 },
    { Name = "Garama and Madundung", Weight = 50, Multiplier = 1 },
    { Name = "Gattatino Nyanino", Weight = 50, Multiplier = 1 },
    { Name = "Gattito Tacoto", Weight = 50, Multiplier = 1 },
    { Name = "Girafa Celestre", Weight = 50, Multiplier = 1 },
    { Name = "Glorbo Fruttodrillo", Weight = 50, Multiplier = 1 },
    { Name = "Gorillo Watermelondrillo", Weight = 50, Multiplier = 1 },
    { Name = "Graipuss Medussi", Weight = 50, Multiplier = 1 },
    { Name = "Guerriro Digitale", Weight = 50, Multiplier = 1 },
    { Name = "Job Job Job Sahur", Weight = 50, Multiplier = 1 },
    { Name = "Karkerkar Kurkur", Weight = 50, Multiplier = 1 },
    { Name = "Ketchuru and Musturu", Weight = 50, Multiplier = 1 },
    { Name = "Ketupat Kepat", Weight = 50, Multiplier = 1 },
    { Name = "La Cucaracha", Weight = 50, Multiplier = 1 },
    { Name = "La Extinct Grande", Weight = 50, Multiplier = 1 },
    { Name = "La Grande Combinasion", Weight = 50, Multiplier = 1 },
    { Name = "La Karkerkar Combinasion", Weight = 50, Multiplier = 1 },
    { Name = "La Sahur Combinasion", Weight = 50, Multiplier = 1 },
    { Name = "La Vacca Saturno Saturnita", Weight = 50, Multiplier = 1 },
    { Name = "Las Capuchinas", Weight = 50, Multiplier = 1 },
    { Name = "Las Sis", Weight = 50, Multiplier = 1 },
    { Name = "Las Tralaleritas", Weight = 50, Multiplier = 1 },
    { Name = "Las Vaquitas Saturnitas", Weight = 50, Multiplier = 1 },
    { Name = "Lerulerulerule", Weight = 50, Multiplier = 1 },
    { Name = "Lionel Cactuseli", Weight = 50, Multiplier = 1 },
    { Name = "Lirilì Larilà", Weight = 50, Multiplier = 1 },
    { Name = "Los Bombinitos", Weight = 50, Multiplier = 1 },
    { Name = "Los Bros", Weight = 50, Multiplier = 1 },
    { Name = "Los Chicleteiras", Weight = 50, Multiplier = 1 },
    { Name = "Los Combinasionas", Weight = 50, Multiplier = 1 },
    { Name = "Los Crocodillitos", Weight = 50, Multiplier = 1 },
    { Name = "Los Hotspotsitos", Weight = 50, Multiplier = 1 },
    { Name = "Los Matteos", Weight = 50, Multiplier = 1 },
    { Name = "Los Noobinis", Weight = 50, Multiplier = 1 },
    { Name = "Los Nooo My Hotspotsitos", Weight = 50, Multiplier = 1 },
    { Name = "Los Orcalitos", Weight = 50, Multiplier = 1 },
    { Name = "Los Spyderinis", Weight = 50, Multiplier = 1 },
    { Name = "Los Tacoritas", Weight = 50, Multiplier = 1 },
    { Name = "Los Tipi Tacos", Weight = 50, Multiplier = 1 },
    { Name = "Los Tralaleritos", Weight = 50, Multiplier = 1 },
    { Name = "Los Tungtungtungcitos", Weight = 50, Multiplier = 1 },
    { Name = "Matteo", Weight = 50, Multiplier = 1 },
    { Name = "Noobini Pizzanini", Weight = 50, Multiplier = 1 },
    { Name = "Nuclearo Dinossauro", Weight = 50, Multiplier = 1 },
    { Name = "Odin Din Din Dun", Weight = 20, Multiplier = 3 }, -- Sounds Rare
    { Name = "Orangutini Ananassini", Weight = 50, Multiplier = 1 },
    { Name = "Orcalero Orcala", Weight = 50, Multiplier = 1 },
    { Name = "Pakrahmatmamat", Weight = 50, Multiplier = 1 },
    { Name = "Pandaccini Bananini", Weight = 50, Multiplier = 1 },
    { Name = "Penguino Cocosino", Weight = 50, Multiplier = 1 },
    { Name = "Perochello Lemonchello", Weight = 50, Multiplier = 1 },
    { Name = "Piccione Macchina", Weight = 50, Multiplier = 1 },
    { Name = "Pipi Avocado", Weight = 50, Multiplier = 1 },
    { Name = "Pipi Corni", Weight = 50, Multiplier = 1 },
    { Name = "Pipi Kiwi", Weight = 50, Multiplier = 1 },
    { Name = "Pipi Potato", Weight = 50, Multiplier = 1 },
    { Name = "Pot Hotspot", Weight = 50, Multiplier = 1 },
    { Name = "Quivioli Ameleonni", Weight = 50, Multiplier = 1 },
    { Name = "Rhino Toasterino", Weight = 50, Multiplier = 1 },
    { Name = "Salamino Penguino", Weight = 50, Multiplier = 1 },
    { Name = "Sammyni Spyderini", Weight = 50, Multiplier = 1 },
    { Name = "Sigma Boy", Weight = 30, Multiplier = 2 },
    { Name = "Sigma Girl", Weight = 30, Multiplier = 2 },
    { Name = "Spaghetti Tualetti", Weight = 50, Multiplier = 1 },
    { Name = "Spioniro Golubiro", Weight = 50, Multiplier = 1 },
    { Name = "Strawberry Elephant", Weight = 50, Multiplier = 1 },
    { Name = "Strawberrelli Flamingelli", Weight = 50, Multiplier = 1 },
    { Name = "Svinina Bombardino", Weight = 50, Multiplier = 1 },
    { Name = "Talpa Di Fero", Weight = 50, Multiplier = 1 },
    { Name = "Te Te Te Sahur", Weight = 50, Multiplier = 1 },
    { Name = "Ti Ti Ti Sahur", Weight = 50, Multiplier = 1 },
    { Name = "Tigrilini Watermelini", Weight = 50, Multiplier = 1 },
    { Name = "Tigroligre Frutonni", Weight = 50, Multiplier = 1 },
    { Name = "Tim Cheese", Weight = 50, Multiplier = 1 },
    { Name = "Tipi Topi Taco", Weight = 50, Multiplier = 1 },
    { Name = "To to to Sahur", Weight = 50, Multiplier = 1 },
    { Name = "Torrtuginni Dragonfrutini", Weight = 50, Multiplier = 1 },
    { Name = "Tracoducotulu Delapeladustuz", Weight = 50, Multiplier = 1 },
    { Name = "Tralaledon", Weight = 50, Multiplier = 1 },
    { Name = "Tralalero Tralala", Weight = 50, Multiplier = 1 },
    { Name = "Tralalita Tralala", Weight = 50, Multiplier = 1 },
    { Name = "Trenostruzzo Turbo 3000", Weight = 50, Multiplier = 1 },
    { Name = "Tric Trac Baraboom", Weight = 50, Multiplier = 1 },
    { Name = "Trippi Troppi", Weight = 50, Multiplier = 1 },
    { Name = "Trippi Troppi Troppa Trippa", Weight = 50, Multiplier = 1 },
    { Name = "Trulimero Trulicina", Weight = 50, Multiplier = 1 },
    { Name = "Tukanno Bananno", Weight = 50, Multiplier = 1 },
    { Name = "Tung Tung Tung Sahur", Weight = 50, Multiplier = 1 },
    { Name = "Unclito Samito", Weight = 50, Multiplier = 1 },
    { Name = "Urubini Flamenguini", Weight = 50, Multiplier = 1 },
    { Name = "Zibra Zubra Zibralini", Weight = 50, Multiplier = 1 },
}

-- Rarity Layers: Elements
GameConfigs.ELEMENTS = {
    { Name = "Plastic", Weight = 70, Multiplier = 1 },   -- x1
    { Name = "Gold",    Weight = 20, Multiplier = 3 },   -- x3
    { Name = "Void",    Weight = 8,  Multiplier = 5 },   -- x5
    { Name = "Glitch",  Weight = 2,  Multiplier = 10 },  -- x10
}

-- Size Range
GameConfigs.SIZE_MIN = 0.5
GameConfigs.SIZE_MAX = 3.0

return GameConfigs